% load_envelope.m
%
% Loads the pre-computed Glasgow equilibrium envelope.
% Runtime cost is essentially zero — this is just a file load.
%
% USAGE
%   envelope = load_envelope(mat_filepath)
%
% INPUT
%   mat_filepath : full path to equilibrium_envelope.mat
%                  generated by preprocess_glasgow_data.m
%
% OUTPUT
%   envelope : struct with fields X_km, a_km, b_km, theta_rad,
%              scale_factor, safety_margin, L1_glasgow_km, L1_spice_km,
%              X_optimal_km, a_at_optimal, b_at_optimal, and more.
%              See preprocess_glasgow_data.m for full field list.
%
% See also: preprocess_glasgow_data, check_position_valid

function envelope = load_envelope(mat_filepath)

if ~isfile(mat_filepath)
    error(['[load_envelope] File not found: %s\n' ...
           'Run preprocess_glasgow_data.m first to generate it.'], ...
           mat_filepath);
end

data     = load(mat_filepath, 'envelope');
envelope = data.envelope;

fprintf('[load_envelope] Loaded envelope from: %s\n', mat_filepath);
fprintf('  Created : %s\n',   envelope.date_created);
fprintf('  X range : [%.0f, %.0f] km\n', min(envelope.X_km), max(envelope.X_km));
fprintf('  Optimal : X=%.0f km, a=%.0f km, b=%.0f km\n\n', ...
        envelope.X_optimal_km, envelope.a_at_optimal, envelope.b_at_optimal);

end